### ISSUE TITLE
loading indicator when loading extension

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1005]
Update ExtensionView Component

**Comment by maxbates** [comment]
@jlachoff did you want to give me a new loader?

**Comment by jlachoff** [comment]
Sure here you go:

[cid:53015A9F-4EA3-4F6F-AC1D-CD233B5905BB@ads.autodesk.com]

[cid:31468130-9DF7-4D32-BAAA-9629BD6D0C84@ads.autodesk.com]

On Oct 17, 2016, at 10:58 AM, Maxwell Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


@jlachoff<https://github.com/jlachoff> did you want to give me a new loader?

**Comment by jlachoff** [comment]
Ugh. Attachments didn't come through.

**Comment by jlachoff** [comment]
![image](https://cloud.githubusercontent.com/assets/15033635/19452733/03d88bdc-9467-11e6-8f49-7b78dbd363fb.png)

![image](https://cloud.githubusercontent.com/assets/15033635/19452748/1269be96-9467-11e6-9cf3-ac3504f8a95f.png)

**Comment by jlachoff** [comment]
24 pt ARTIFAKT ELEMENT BOLD #DFE2EC

Animation:
Fade to visible 250 ms
Hold for 2 seconds
Fade to transparent 250 ms
Repeat

**Comment by jlachoff** [comment]
Sorry, I accidentally hit, "Close and comment" cuz I'm a noob.
