### ISSUE TITLE
More Inline Editing Tweaks

### ISSUE THREAD

**Issue by duncanmeech** [Autodesk/genetic-constructor#1083]
1. Let's lose the black outline surrounding the active text editing fields;
2. We need to get the arrow pointer to be a traditional button cursor (i.e.,the gloved hand finger pointing cursor), whenever hovering over the button regions;
3. On blocks, (only) we we don't need to show the gray button at all. Instead we should make the hover state invisible, so the only indication that the text is clickable is going to be that the arrow cursor changes to a finger pointer cursor. If the block has a glyph, upon hover we can change the glyph to the pencil icon, too. If it doesn't, don't use the pencil at all.
4. On the Project and Construct names, is it possible for the hover state to get some padding on the left side, without repositioning the text? Right now it's butted right up against the text.
5. On blocks, currently the hover state is switching font from Helvetica to Artifakt. This will become more noticeable if we do my item #3 above. It should stay Helvetica.
6. When a block is in active text editing mode, let's just make the entire block a white rectangle - no black border, and no corner rounding necessary.
7. When editing a Project name, the change in the background color of the entire project div, (originally this was how we indicated focus) is no longer helpful. let's eliminate that.

**Comment by maxbates** [comment]
@duncanmeech is this done?
