### ISSUE TITLE
New sketch block - List block

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1106]

**Comment by jlachoff** [comment]
I have posted an updated design that includes the new sketch block for combinatorial lists, and the asset has been added to the assets > SBOL folder.
Note that dragging out a list block should not place the list block glyph in the resulting list block -- it should just make an empty list block labeled "New list block" with no glyph. The user can add a glyph via the inspector panel or by dragging any other type of sketch block from the library and dropping it on the new list block.

**Comment by cojofra** [comment]
list svg
https://autodesk.box.com/s/84he1psvevaoieank3x9t07g488ste98
