### ISSUE TITLE
(Storage) HEAD operations to check for existence

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1112]
api/projects/projectId?owner=__

want version, omit data

**Comment by dhylbert** [comment]
In `use-db` branch:

`HEAD /api/projects/:projectId`

Optional query params:
 * owner - owner UUID
 * version - integer version

Query parameters further limit the project search. Version should only be used to check the existence of a particular version.

Returns:
 * 200 if the project exists. The HTTP header `Latest-Version` is returned with the latest version of the specified project.
 * 404 if the project doesn't exist, or doesn't belong to the specified user.
 * 500 if server error
