### ISSUE TITLE
(Storage) route to check if user set up

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1117]
HEAD operation may make sense

for use when check user setup, need to make sure they have projects, and if not, then set them up

`/api/projects/owner/ownerId`
200 - most recent projectId
404 - not set up

**Comment by dhylbert** [comment]
In `use-db` branch:

`GET /api/projects/owner/:ownerId`

* Returns 200 HTTP status code and an HTTP Header `Last-Project` value with the id of the last project updated for this owner if the owner has at least one saved project.
* Returns 404 if the owner has no saved projects.
* Returns 500 on server error.

**Comment by dhylbert** [comment]
`HEAD /api/projects/owner/:ownerId` now returns an additional header, `Last-Project-UUID`. You can use the result of this with the following API to load the last project the user updated as quickly as possible.

`GET /api/projects/uuid/:uuid`
 * Returns 200 and the project object with blocks
 * Doesn't require `version` or `owner` as they are implied by `UUID`.
