### ISSUE TITLE
(Storage) table for orders

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1118]
orders are tied to a project. they are not versioned. will give you order ID

index over: `id`, `projectId`, `projectVersion`, owner

order exists (with owner query param optional)
Get order, given orderId (and projectId?)
list orders, given projectId
list orders, given owner
write order - POST id, owner, data (id, projectId, projectVersion, etc.)

**Comment by dhylbert** [comment]
@maxbates Proposed schema for Orders:
```
orderId
projectId,
projectVersion,
type,
data,
// system fields
status, // 0 or 1 for archiving
createdAt,
updateAt,
```
Like Snapshots, you'll need to pass `orderId`, `projectId`, `type`, and `data` on create or update. Note, there is NOT a `message` column like Snapshot. Ok?

**Comment by maxbates** [comment]
sounds good

**Comment by maxbates** [comment]
bump.

need to be able to get an order by order ID (and will know its project ID) - cannot guarantee that a projectId + project version will lead to unique orders.
