### ISSUE TITLE
(Storage) Snapshot support

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1120]
Snapshots are a special type of version. 

They should be able to specify a message string, and an object of tags.

They can create another numeric version, but should be indexed so it is easy to just get all the snapshots, and index over message + each of the tags. 

Later, may want to be able to see all the tags or filter by those tags

**Comment by dhylbert** [comment]
In `use-db` the following Snapshot functionality is now provided:

`POST /api/snapshots` -> create/update a snapshot
```
var postBody = {
  owner: UUID,
  projectId: UUID,
  projectVersion: Integer,
  message: non-null string,
  tags: JSON,
}
```
 * Looks up the unique project record for the projectId and version
 * Returns 404 if the projectId and version do not exist
 * Creates a new snapshot record for the unique project record
 * Updates `message` and `tags` of current snapshot if one already exists

`GET /api/snapshots/:projectId` -> fetch a snapshots
`GET /api/snapshots/:projectId?version=47`
 * Returns array of Snapshot objects for the given project, limited to a specific version (array of size 1) if `version` is provided.
 * Returns 404 if no Snapshots exist for the given project, and optionally version.

`GET /api/snapshots/uuid/:uuid` -> fetch a snapshot
 * Returns the Snapshot object for the given Snapshot UUID
 * Returns 404 if no Snapshot object exists for given Snapshot UUID

`DELETE /api/snapshots/uuid/:uuid` -> delete a snapshot
 * Permanently deletes the Snapshot object for the given Snapshot UUID
 * Returns 404 if no Snapshot object exists for given Snapshot UUID

`POST /api/snapshots/tags` -> fetch using JSON tags
 * Post `tags` specifier as request body, not `{ tags: tags }`.
 * Returns array of Snapshot objects that match the posted tags object.
 * This is not an exact match. Any snapshots that have tags that a subset of the JSON object provided will match.
 * Returns 404 if no Snapshots match the tags

**Comment by dhylbert** [comment]
In `use-db` branch, you can now omit `projectVersion` from the post body to `POST /api/snapshots` to create a Snapshot using the latest version of the `projectId` passed in the post body.
