### ISSUE TITLE
(Storage) Get project manifests

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1121]
Need a route to just get all of the project manifests (`data.project`) for a given user

When the app loads, it loads all of the users projects -- just the project, not the blocks

**Comment by dhylbert** [comment]
@maxbates Should `GET /owner/:ownerId` return projects without blocks by default and then return projects with blocks if an optional query parameter is provided?

`GET /owner/:ownerId` -> Array of Projects w/o blocks
`GET /owner/:ownerId?blocks=true` Array of Projects w/ blocks

**Comment by dhylbert** [comment]
This is done in the `use-db` branch.
