### ISSUE TITLE
(Storage) Snapshots should add type column

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1131]
was expecting separate field. should be a tag (overriding one)

**Comment by maxbates** [comment]
@dhylbert i will add the type to tags, dont need another column

**Comment by dhylbert** [comment]
@maxbates I have to edit the schema to support archiving, so I can still add a "type" column. Also, if you want to stop deletion based on type, you may want it as a separate column. If you DO want a separate column, please specify the type; Integer or String.

**Comment by maxbates** [comment]
lets do it then - String

**Comment by dhylbert** [comment]
`type` is has been added to the Snapshot schema in the `use-db` branch. It is required for all updates and creates.

@maxbates Do we need ability to query snapshots by type? And if so, projectId + type as well?
