### ISSUE TITLE
Unexpected behavior in sequence viewer upon list block selections

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1137]
When having several list blocks the sequence viewer shows the correct sequence based on the option selected, however when selecting an option it does not focus that block of sequence. It tends to stick with either the first or last (screencast) block in the construct.

https://drive.google.com/file/d/0B59XgjZRlAfIMi1mNExHVUNUZlU/view?usp=sharing

**Comment by duncanmeech** [comment]
Should show the current selection when changed in the construct viewer.
