### ISSUE TITLE
Bottom panel has an all white background, instead of the design shown in the mockup.

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1169]
Here's a link to the mockup on Box: https://autodesk.box.com/s/5rqg5qjz3msldvfczvfardsca9934g5n
Here's what it looks like on QA:

![image](https://zube.io/files/Autodesk/64196a4f5a8cddcf49c5834fdc9f0d04.png)

**Comment by duncanmeech** [comment]
Fixed in the main UI PR.
