### ISSUE TITLE
Search panel layout fixes

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1176]
Link on Box to what it should look like:
https://autodesk.box.com/s/2s870nwasxyir30zehnp20s3va47hd1u
and
https://autodesk.box.com/s/b1o5lj1oygof0vt8v7t6886i7odr6v6w

Here's a screen capture of the current build:
https://autodesk.box.com/s/5rqg5qjz3msldvfczvfardsca9934g5n

**Comment by cojofra** [comment]
- [ ] add scroll bar when needed
- [ ] font for by source and by kind s/b Helvetica
- [ ] long result names wrap on selection
- [ ] add pixel margins according to spec

**Comment by cojofra** [comment]
@jlachoff could you add pixel numbers for margins onto the spec or add here?

**Comment by jlachoff** [comment]
Zeplin spec has been updated and includes all measurements -- if you need any measurements that are not there, please let me know! Thanks.
