### ISSUE TITLE
Write up technical spec for Vendor Authentication and ordering

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1190]
API spec we are giving to Thermo

**Comment by maxbates** [comment]
WIP: https://docs.google.com/document/d/13VS7_84oQiTZtMmuFtQ9cNJEIz4deGM4uTc3wYQDUzY

**Comment by maxbates** [comment]
Is this enough? I dont think it make sense to give them an overly specific detailed API, but may make sense that its a bit more specific than this. I am not clear on what they would want
