### ISSUE TITLE
Sign-up bug

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1198]
When registering for an account the register button does not turn dark grey even if all information is provided.

![Screen Shot 2016-12-06 at 4.58.18 PM.png](https://zube.io/files/Autodesk/3a7ba702d58bc017c6e7e198ad0d9fcf.png)

**Comment by duncanmeech** [comment]
works for me. Can you provide a more specific sequence of actions that reproduce this problem.

**Comment by cojofra** [comment]
I added a video here:
https://drive.google.com/file/d/0B59XgjZRlAfITlR3WWs4bGQtU0E/view?usp=sharing

Using google chrome on macbook air:
Goto www.geneticconstructor.com
Sign-in -> register
Fill out form
Agree to terms
... register button stays inactive
adjust email or password 
... register button becomes active
