### ISSUE TITLE
Route to fetch blocks without a role

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1218]
Currently, can fetch blocks by role... we return all the blocks with no role with a count, but then you can't actually get those blocks. 

Should be able to fetch all blocks without a role

**Comment by dhylbert** [comment]
The Storage API exposes `GET /api/blocks/:ownerId/:role` that will fetch all blocks for a given user (`ownerId`) and role (`role`).

Is that what you want? Or you want a route that returns all blocks for a user (`ownerId`) regardless of `role` or `name`?

**Comment by dhylbert** [comment]
Ok, per offline discussion with @maxbates the request is for fetching all blocks where `role` is `null` or `undefined`. A role of `''` will NOT be included unless otherwise specified.
