### ISSUE TITLE
Visual redesign - rough cut issues

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1233]
Here's a link to the write up. Also posted this on Slack:

https://autodesk.box.com/s/chwkguedxwbs0ocbuk5b817g8rld3kqy

**Comment by cojofra** [comment]
translated feedback from document into this board:
https://zube.io/autodesk/genome-designer/w/ux-redesign/sprintboard?where%5Bsprint_id%5D=14166
