### ISSUE TITLE
GSL session saving broken

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1239]
1. Code something in GSL
2. Run
-> you see 1 construct
3. Change name or something small 
-> you the change in the one construct
4. Reload the page
-> I always get a "not everything maybe saved warning" (even if the next thing does not happen)
-> it may happen that the last script change was not properly saved (see a to b appendix change in the video)
5. Run the same GSL code that is saved to your project again
-> a second construct is created
It should overwrite the first one again.
https://drive.google.com/open?id=0B59XgjZRlAfId0dfUlItaDhzNm8

**Comment by maxbates** [comment]
https://github.com/autodesk-bionano/gc-gsl-editor/pull/11
