### ISSUE TITLE
Export assets in pixels as opposed to points

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1241]
most/all assets are in points right now - when using them at the defined size in pixel that makes them fuzzy.

**Comment by jlachoff** [comment]
I will remake all of the assets in Sketch and post an update here once it's done.

**Comment by jlachoff** [comment]
I've completed rebuilding the assets and have published them here: https://autodesk.box.com/s/3x1j9j2jcmehhkdbxrhkg8e40pb4ybtl
Please replace ALL of the old assets with the new ones. Thanks!
