### ISSUE TITLE
Context menus - fixes

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1244]
- [ ] color bg: #DFE2EC
- [ ] color type: #161922
- [ ] color separator lines: #ffffff
- [ ] color inactive item type: 585B69
- [ ] type size 14pt
- [ ] menu shadow: 10px; no offset; 20% transparency of #263142
- [ ] right click on construct canvas background also needs to trigger menu - not just construct name line

**Comment by duncanmeech** [comment]
#type size ... I assume you mean 14px since 14pt in AARP scale.
For shadow on menus could you use something like: 
http://www.cssmatic.com/box-shadow
 and send me the css.

**Comment by jlachoff** [comment]
Hi Duncan - I just posted a quick and dirty menu spec to Zeplin: https://zpl.io/ZjHJhR
thanks! Joe
