### ISSUE TITLE
Search panel improvements

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1248]
- [x] implement new progress bar
- [x] implement progress bar upon load more
- [x] correct inspector panel visualization 

Progress bar spec:
https://autodesk.app.box.com/files/0/f/11934437658/1/f_100700080363

Inspector panel spec:
https://autodesk.app.box.com/files/0/f/11934437658/1/f_104418390866

**Comment by jlachoff** [comment]
Fit and finish will be low without this in the release.

**Comment by cojofra** [comment]
@cojofra need to update after testing dev again - there maybe only 1 more bug on this
