### ISSUE TITLE
New sketch block - backbone

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1250]
Backbone block glyph needs to be added to the sketch library along with use restriction as highlight in this doc:
https://autodesk.box.com/s/ypbr3mdwl5ch8r2a3bn36rsmspmyxo00

**Comment by jlachoff** [comment]
In addition to the items shown in the spec above:

1.A backbone block can be a list block. (the list should only appear on the left-most/opening side of the backbone block; (not that this should also require fixing the list block behavior (open but in zube));

2. When the user converts a construct from circular (i.e., having a backbone block)  to linear, (removing the backbone), any sequence data inside the backbone should become normal block data"

**Comment by cojofra** [comment]
summary
1. Remove symbol part from bb inspector.
2. fix all drag and drop and copy issues that you already know about
3. estimate enabling list block
4. add "Linearize" menu option to bb blocks or circular constructs -> converts bb block into no symbol
5. add "Circularize" menu option to constructs -> all blocks get children of bb block
6. add "Circularize" menu option to continous block selection -> all selected blocks become children of bb, non selected blocks are inserted into the scar - left to right starting from right most edge of bb block selection

**Comment by jlachoff** [comment]
The menu spec uses slightly different terms than what Conny mentions above. Assuming this is just an oversight, please use the spec: zpl.io/18Mmu

**Comment by cojofra** [comment]
@jlachoff yes thanks - I was just typing from memory and not inferring the actual wording. thanks for linking the spec

**Comment by cojofra** [comment]
@duncanmeech I think you took out the list block conversion from the inspector for bb blocks, correct? There is still the conversion option in the context menu. and that leads to funny visualization

**Comment by cojofra** [comment]
@duncanmeech found a bug when looking at non-existen hidden blocks. reproducible
video:
https://drive.google.com/open?id=0B6j6XBxk1VvIQjNEOW1FTVg0Wm8
 - [ ] creating a weird down line for hierarchical bb when viewing hidden 
- [ ] spaces appear when clicking on canvas
