### ISSUE TITLE
Adding new tool bars

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1255]
- [ ] Project toolbar
- [ ] Construct toolbar

Resources:
https://autodesk.box.com/s/4ekdr8zmeypt5xpc12nmn9g9ydcf4038
https://autodesk.box.com/s/m7dziqh6nmei66hddc24hryiynk7f4em

**Comment by jlachoff** [comment]
I think this is required for release. The context menus don't contain every command.
