### ISSUE TITLE
Inspector - Plugins panel

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1262]
- [x] Margin before and after arrow should be 12px
- [x] expandable content bg color: lighter grey eeeff3
- [x] Plugin titles font-weight: bold
- [x] Plugin metadata (labels and content) type: Helvetica
- [x] Plugin content font-weight: normal

**Comment by jlachoff** [comment]
Fit and finish, should be required for release imho.

**Comment by duncanmeech** [comment]
![Screen Shot 2017-02-13 at 9.33.48 AM.png](https://zube.io/files/Autodesk/db931f4222dfe433c0d66d81169cbb48.png)
