### ISSUE TITLE
Inspector - Feedback panel

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1264]
- [ ] Linkedin link type: DNS -> DNA
- [ ] Email - add a message: "Check out Autodesk Genetic Constructor: http://geneticconstructor.com"
- [ ] Fix issue with different screen scalings - on Conny's big screen at work the social media bar is cut in half - and I can't scroll.

**Comment by duncanmeech** [comment]
Scrolling fixed in previous PR
NOTE: mailto: links cannot contain HTML so link to geneticconstructor.com is plain text, although most mail clients would auto link it.
