### ISSUE TITLE
heap analytics calls happen when doing local development

### ISSUE THREAD

**Issue by dhylbert** [Autodesk/genetic-constructor#1287]
disable heap analytics calls locally

**Comment by maxbates** [comment]
This depends on whether `process.env.NODE_ENV === 'production'` when index.pug is rendered, and is only enabled in production.

**Comment by dhylbert** [comment]
I don’t think this is the case. When I run the app locally, NOT setting `NODE_ENV` equal to ‘production`, I see calls to heap analytics in the console network log.

**Comment by maxbates** [comment]
You sure?
https://github.com/Autodesk/genetic-constructor/blob/master/server/server.js#L191 https://github.com/Autodesk/genetic-constructor/blob/master/src/content/index.pug#L18

**Comment by maxbates** [comment]
oh. yup. thats just google analytics. heap is being used in dev...

**Comment by maxbates** [comment]
Do you still want this open @dhylbert
