### ISSUE TITLE
Bug in the color assignments

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1297]
at least in the natural pallet

![Screen Shot 2017-01-10 at 4.04.19 PM.png](https://zube.io/files/Autodesk/fad09fba518ee0c8d27b746aaed3a6cd.png)
- [x] I select green and it shows yellow. Just one example. All I tried right now with natural, bright and pastel did not work.
The only one that works is anime right now.
- [x] Sequence viewer does not show the correct color
- [x] Children don't get the right pallet asigned

**Comment by cojofra** [comment]
I think the first one may have been fixed with implementing the new design already

**Comment by duncanmeech** [comment]
Most of these were addressed in previous PR's. I have updated the sequence viewer to use the chosen palette and to be responsive to palette changes.
