### ISSUE TITLE
Menu item extensions

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1299]
Support for menu item extensions, i.e. extensions which render as menu item commands.

First example: `boost`. Boost need to register menus for codon optimization and sequence verification. They should be able to call actions in the app.

Each extension should be nested in the menu under its name.

example format:

```js
constructor.extensions.register(
  'boost',
  'menu',
  [{
    text: 'BOOST',
    type: 'block',
    items:  [{
      text: 'Codon Optimize...',
      disabled: (block) => {},
      action: (block) => {},
    }, ...],
  }]
);
```

**Comment by duncanmeech** [comment]
See my comments on this card for running menus in extensions.
https://zube.io/autodesk/genome-designer/c/1391
