### ISSUE TITLE
GSL bug - code does not save properly on first time use

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1309]
Make a new project.
Open gsl
Make something like pADH1
Run
View sequence in sequence viewer
Look back at the gsl window - pADH1 will be gone

editing in the same window now seems to save.

**Comment by maxbates** [comment]
cannot replicate...

**Comment by cojofra** [comment]
made a short video: https://drive.google.com/open?id=0BzUjRX4AzyD8YUlUVzlzVGpodE0
it does not happen every time. but about every second time I do this sequence I lose data
new project
write gsl
look at sequence
look at gsl

**Comment by cojofra** [comment]
not happening anymore.
