### ISSUE TITLE
Sign in dialog has no "Keep me signed in" checkbox/functionality

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1334]

**Comment by jlachoff** [comment]
https://zpl.io/2i9S1L

**Comment by maxbates** [comment]
This is a new feature, isn't it? @dhylbert does our auth support htis?

**Comment by jlachoff** [comment]
Hmmm. I thought we had this in the version we just retired, no? I'm open to having imagined it. It's possible that we just were not requiring re-authentication unless you sign out explicitly - in other words, like they had check just such a box...

**Comment by maxbates** [comment]
i dont think we handled the session differently based on that box (i.e. authenticated for session, or cookie set for 30 days or whatever)

**Comment by jlachoff** [comment]
I'm fine leaving it out - I honestly thought we had it, but I must have been confusing the implementation, which kind of delivers a workaround for the explicit feature, with the feature actually being there, (since I did not have to sign in...) Disregard.
