### ISSUE TITLE
(Commons) UI - Publishing modal

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1343]

**Comment by jlachoff** [comment]
For dialog specification, please see: https://app.zeplin.io/project.html#pid=581d0bc0b7502238616341cb&dashboard&tags=publish 

The 3 access point for the Publish dialog is described in this spec: https://autodesk.box.com/s/wdwy8cop9leyf5u6uvkr4wovavx8ya5v

The menu spec has also been updated to reflect access points in menus:
https://autodesk.box.com/s/m7dziqh6nmei66hddc24hryiynk7f4em
