### ISSUE TITLE
GSL menu not working due to missing CSS

### ISSUE THREAD

**Issue by dhylbert** [Autodesk/genetic-constructor#1391]

**Comment by duncanmeech** [comment]
GSL should define its own CSS. Extensions should not depend on CSS from the app to function since it is subject to change at anytime.

**Comment by dhylbert** [comment]
Drew or Max to update CSS references in the GSL client code.

**Comment by duncanmeech** [comment]
You should not rely on or hack in the CSS from the main app. There is a ui action ( function! ) that you can call from any extension to run a modal menu. Here is an example from the Sequence Viewer.

  showContentMenu(event) {
    const showMenu = window.constructor.api.ui.uiShowMenu;
    invariant(showMenu, 'expected uiShowMenu api to be available');
    showMenu([
      {
        text: 'Menu Item 1',
        action: () => { alert('1')},
      },
      {
        text: 'Menu Item 2',
        disabled: true,
        action: () => { alert('1')},
      },
      {
        text: 'Sub Menu',
        menuItems: [
          {
            text: 'Sub Menu Item 1',
            action: () => { alert('Sub 1')},
          },
          {
            text: 'Sub Menu Item 2',
            action: () => { alert('Sub 2')},
          },
        ],
      },
      {
        text: 'Menu Item 3',
        action: () => { alert('1')},
      },
    ], {
      x: event.pageX,
      y: event.pageY,
    });
  };

It looks like this:

![Screen Shot 2017-02-10 at 9.12.07 AM.png](https://zube.io/files/Autodesk/c55c2bc316b93f459dd9552fccc9b628.png)
