### ISSUE TITLE
Selected Project, Construct, or Block should have blue background when selected

### ISSUE THREAD

**Issue by dhylbert** [Autodesk/genetic-constructor#1395]

**Comment by cojofra** [comment]
selected, means clicked, but not necessarily open in canvas

**Comment by maxbates** [comment]
@jlachoff what about what it is selected and active (e.g., you are inspecting the project and it is the one in the design canvas)

**Comment by jlachoff** [comment]
Rule: Only one thing gets a rectangle-- the thing currently being inspected.
Rule: The hover rectangle doesn't count for Rule 1.
1. To inspect an item in the list, click it. the background turns light gray;
1a. In the inspector, data fields are inactive and should appear so.
2. To inspect the active project or construct or block, click it, the background turns dark blue
