### ISSUE TITLE
New TOS

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1405]
We need to integrate new terms of service.
 - [ ] terms of service should be hosted on ...autodesk.com/tos
 - [ ] sign-up modal should say "I agree to the Beta Cloud Services Terms of Service ..." where Beta Cloud Services Terms of Service is the link to our copy of services
 - [ ] terms of service link in the help panel also needs to link there
 - [ ] terms of service link on landing page also needs to link there
 - [ ] basic styling on tos page: logo, headings and paragraphs

TOS here:
https://autodesk.box.com/s/5cimfngajepbizc41pr4y06ylekmtg6w

**Comment by maxbates** [comment]
@cojofra Do i need to put a HTML version? Can you generate one then? Or can I just host a PDF
