### ISSUE TITLE
Catch tracking urls /?...

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1414]
Google and Autodesk links add a tracking portion onto the link such as
`/?link=...`
The common part always seems to be `/?`
We should catch alls links that do not connect to app path and serve the landing page for those - so that referral links all lead to the correct page.

**Comment by dhylbert** [comment]
Unknown query parameters should already be ignored. Is that not happening?

**Comment by cojofra** [comment]
`/?..../ goes to the sign-in page and not our landing page
I think everything unknown currently goes to sign-in like `/?buha`
I need these to go to landing and not sign-in

**Comment by maxbates** [comment]
server.js sends to landing page id route === '/' -- need to ignore query parameters to route properly
