### ISSUE TITLE
Delete project modal font color

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1452]
is this intentional?

![Screen Shot 2017-02-09 at 4.32.08 PM.png](https://zube.io/files/Autodesk/1f316bc39b69e3e856dced887d4e3f6e.png)

**Comment by jlachoff** [comment]
No.

**Comment by jlachoff** [comment]
Here's what the original dialog looked like on my drawing board. It used to look roughly similar to this in the running product. (The dark border is just there to indicate the background- the dialogs had no border.

![image](https://cloud.githubusercontent.com/assets/15033635/22828359/abd5b6da-ef51-11e6-9443-8df4b4db39b0.png)
