### ISSUE TITLE
Construct panel has some obsolete items in inspector

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1460]
- [ ] should NOT show symbol picker
- [ ] "Construct rules" section if lists or hidden blocks are included should NOT show (only for blocks please)

**Comment by duncanmeech** [comment]
should 'not' show symbol picker?

**Comment by cojofra** [comment]
yes, sorry NOT show

**Comment by duncanmeech** [comment]
I can't get rules to appear for constructs so I assume I already fixed that previously.

**Comment by cojofra** [comment]
@duncanmeech I figured it out - it only shows for *empty* constructs - so does the symbol picker btw. making a new card
