### ISSUE TITLE
establish 2 CNAMEs for the bionano blog

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1478]
x | Name, Label, or Host field | Destination, Target, or Points To field
1 | blog | ghs.google.com
2 | dsn646cqdngn | gv-wlqdf7sorog6mi.dv.googlehosted.com

**Comment by cojofra** [comment]
To add all the content we produce to our domain we'll need to bring the blog onto our url
These are the 2 cname's I'd need.
@dhylbert if you have time to fit this into this sprint that would be great, otherwise next please

**Comment by dhylbert** [comment]
so...

blog.gctor.bionano.autodesk.com -> ghs.google.com
dsn646cqdngn.gctor.bionano.autodesk.com -> gv-wlqdf7sorog6mi.dv.googlehosted.com

@cojofra ??

**Comment by cojofra** [comment]
good catch, sorry about that. this should just be a sub to the bionano domain.
blog.bionano.autodesk.com -> ghs.google.com
....

This is the what it showed me - so yes I am assuming that mapping is correct
![Screen Shot 2017-02-14 at 8.42.18 AM.png](https://zube.io/files/Autodesk/9718829b8ec463ad874545e23a1c0dda.png)
just for completion: https://support.google.com/blogger/answer/58317

**Comment by dhylbert** [comment]
These CNAME records have been created.

blog.bionano.autodesk.com -> ghs.google.com
dsn646cqdngn.bionano.autodesk.com -> gv-wlqdf7sorog6mi.dv.googlehosted.com
