### ISSUE TITLE
add "Show sequence" and "Hide Sequence" depending on the state to the view menu

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1482]
for both block and construct level

**Comment by jlachoff** [comment]
We have a context menu item in the design for "Edit Sequence".

**Comment by jlachoff** [comment]
Clicking on the logo is supposed to hide/show all panels, too.

**Comment by cojofra** [comment]
oh I had interpreted edit sequence as triggering the edit modal - which is the only way to edit the sequence at this point
