### ISSUE TITLE
Should be able to add blocks to hidden blocks

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#1494]
What is the behavior when they are added? Do they become hidden? Is hidden-ness inherited?

**Comment by duncanmeech** [comment]
Opposite of a card I just completed. @cojofra can weight in here.
Currently a hidden block cannot be dropped on to add children. Using the inspector to change a block with children to a list block appears to remove the children

**Comment by cojofra** [comment]
let's keep it blocked for now. I think this should get revisited and fully designed when we work on templates.
