### ISSUE TITLE
Extra Credit - UI fit and finish punch list

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1509]
Per our discussion today, here are a list of low-hanging fruit/niggly details to tighten up the UI for our 'BIG DEBUT'. None of this is critical, but all of it will improve the overall UX! Thanks.

- [x] Search box style (from Zeplin)
- [x] Text input style - including background color and placeholder text style from Zeplin.
- [x] Field labels in inspector panels s/b Artifact Element 12px colors-mediumDarkGrey
- [x] Color/Palette/Symbol pickers (and the palette tab) should be #33374b
- [x] Sequence Viewer s/b first on left (bottom panel)/top of list in Plugins panel.
- [x] Feedback panel - To: down arrow is word wrapped to second line.
- [x] Feedback panel - bottom matter should not scroll off bottom (unless window is REALLY really short, in which case it is fine).
- [x] Banner notifications: center the text including the space used by the "X" on the right.
- [x] Centered Symbols should be left aligned in Symbol picker and in Sketch Library
- [x] No Symbol display name should be "Blank" — under the icon in the Sketch Library and when you drag out the block.
- [x] Search results - can we tighten up the line spacing so we can see more results? The current spacing has a lot of top/bottom padding.
- [x] New "G" logo (already published to 'assets' on Box) 
- [x] Product name at the top, "Genetic Constructor" s/b ArtifaktElement-Light 20px
- [x] Clicking on the logo should do the same thing as hide/show all panels;
- [x] I will publish updated set of blue rollover assets for the panel icons. (To be used only when the panels are in the Open/visible state.)
- [x] Top and bottom caps of menus a little shorter (requires making the triangular item smaller due to shadow problem).
- [x] Correct text on sketch blocks inventory

**Comment by duncanmeech** [comment]
branch: extra-credit
