### ISSUE TITLE
Color Palette Picker "brick wall"

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1513]
Per this spec: https://zpl.io/Z1KfR5n

The color *palette* picker, (the one with the tabs) has been redesigned so that it is visually differentiated from the *color picker*. The new **palette** picker uses a compact mockup of blocks in the canvas that looks sort of like a low brick wall. This should help to reduce confusion.

**Comment by jlachoff** [comment]
Assigned to Conny for prioritization. Not critical for mvp

**Comment by cojofra** [comment]
oh that is cool! definitely will keep in backlog
