### ISSUE TITLE
Heap analytics error

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1521]
I don't know what I did to trigger this - but maybe someone can tell from this message.
![Screen Shot 2017-02-14 at 11.18.00 PM.png](https://zube.io/files/Autodesk/ea108ef6aa2be48b7f372ff2a9e23192.png)

**Comment by maxbates** [comment]
@cojofra this is on the landing page, landing.html L 469

**Comment by cojofra** [comment]
thanks for checking!
