### ISSUE TITLE
EGF ordering bugs

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1525]
EGF templates have 2 main issues:
- [x] can't review assemblies (see first screenshot)
- [x] when I place an order I get an error message on screen that it couldnt be completed (console 2nd screenshot), but the order goes to EGF (I got the email)

![Screen Shot 2017-02-15 at 11.26.27 AM.png](https://zube.io/files/Autodesk/16951cf78f92bdaae8f339686fb3610d.png)

![Screen Shot 2017-02-15 at 11.27.47 AM.png](https://zube.io/files/Autodesk/329c7920a1194da5fda0e42740ed81e8.png)

**Comment by duncanmeech** [comment]
Fixed in a previous card.

**Comment by maxbates** [comment]
I think EGF has changed their API to prevent large orders. @cojofra do you want to check in with them if you are stil doing standups? or i can email

**Comment by cojofra** [comment]
@maxbates I just had a call this morning. valentin had a question for you anyways (he wanted to email you tomorrow) - so I think its most efficient if you just email/message him

**Comment by cojofra** [comment]
we are only doing weekly standups at this point
