### ISSUE TITLE
Project name overflow

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1544]
Long project names hide the click target to open the project

![Screen Shot 2017-02-16 at 11.49.55 AM.png](https://zube.io/files/Autodesk/212f1683f1f890ed09be8f793dc7aa6d.png)

**Comment by duncanmeech** [comment]
Limit people to shorter project names?

**Comment by cojofra** [comment]
can't you just overflow sooner? like "anti-malarial dr..."
