### ISSUE TITLE
Making block into list block changes "Block Rules" (field label) in info panel to "List Block Rules"

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1554]
Expected behavior: Text of label should remain, "Block Rules" regardless of whether list block is checked or not.

**Comment by maxbates** [comment]
I believe this is actually the expected behavior. This would be a change

**Comment by jlachoff** [comment]
I guess technically you are right - I can't speak to the design intent since I am not the designer. This feature was implemented without design input, and needs to be redesigned. The semantics of changing the label of an option list self reflexively is a poor design choice, and should be fixed. Suggest redesigning the feature.

**Comment by cojofra** [comment]
I'd say that can be revisited when we are implementing the advanced list block design - also clean up the existing design.
