### ISSUE TITLE
Decide what to do with top margin

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1572]
in the original design the first construct was 50px from the top of the page, however that did not consider the presence of the drop target. 
the drop target is 10px and there is an additional 12px margin between the target and the construct. 
if we do not have a drop target, the constructs will move down every time someone wants to drag and drop. this would also be more complex on the technical level. so it's probably best if we can incorporate the droptarget px height and margin into the design. (or remove the top drop target?)
![Screen Shot 2017-02-20 at 3.44.37 PM.png](https://zube.io/files/Autodesk/1589931e23fda3601d2693b563a0c601.png)

**Comment by jlachoff** [comment]
If you take a look at the spec on box: (https://autodesk.box.com/s/2fx34d7zmt4ewwp9cdi892obkugbl5xe) you will notice that the uppermost drop target fits above the first construct, within the 50 px space currently occupied by the project header.

**Comment by jlachoff** [comment]
The spec **did** consider the drop target.

**Comment by cojofra** [comment]
right I see - in the drop spec. sorry I just looked at measurements. 
so what happens with the project header in that case?
hides? or overlay?

![Screen Shot 2017-02-20 at 4.00.48 PM.png](https://zube.io/files/Autodesk/d80f3b7648d70860a0db7c1f4ec0952a.png)

**Comment by jlachoff** [comment]
No, it just sits there, looking pretty. The drop zone does not interfere with the elements inside the header in any way. Once the . user drops the element, it will appear as the top-most element in the area below the 50 px region. Make sense?

**Comment by jlachoff** [comment]
This shows the elements in the Project header - notice there is no conflict:

![image](https://zube.io/files/Autodesk/eb9d61c71cfc0d4a5bde9d8e302320a3.png)

**Comment by cojofra** [comment]
ok but the drop zone technically needs to be a div of the size of the zone so that we can register if someone drops something on it. so the dropzone physically needs to be div occupying some space at all times. also it is specced to appear as a blue bar. 
in this spec: is the project title disappearing because drag and drop is started, or was it just omitted from the sketch? 
![Screen Shot 2017-02-20 at 4.20.48 PM.png](https://zube.io/files/Autodesk/b09f03790882be4b2e5d4f65e916dbf3.png)

**Comment by jlachoff** [comment]
Hi Conny: The spec is not showing the project title, etc. - but it should be. I can't remember why I didn't include it originally, but it was never the design intent that it disappear during activation of the drop zone, to answer your question. If you like I can republish it with that stuff showing. The drop zone fits without overlapping at all with the project header stuff.

**Comment by cojofra** [comment]
I see what you are saying - but I in my view the published specs (measurement vs dropdown) have conflicting info - so I just want to get it right. probably a 5min in person conversation tomorrow is more efficient than zube chatting :)  before standup/sprint planning?
