### ISSUE TITLE
Error 404 page has a CSS issue that is making some of the text invisible.

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1583]
Visit a non-existent page, (e.g., https://geneticconstructor.bionano.autodesk.com/hello)
Notice that there is a strange gap at the end of the paragraph of text, just before the link text:

![image](https://zube.io/files/Autodesk/9c669accd4b399954087f12ae947a1e1.png)

If you click and drag through that awkward space, you'll notice that you are actually highlighting text that is not visible:

![image](https://zube.io/files/Autodesk/c2171ba8a2d0e93eb37c3fdb4d4aac19.png)

There also appears to be a missing space character at the end of the hidden characters.

This is occurring on the error 404 page. Can we also please check the other error page to make sure it is also not similarly broken? Thanks.

**Comment by maxbates** [comment]
this is in-app content
