### ISSUE TITLE
Default Attribution string is too aggressive

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1637]
The design intent was different than what got built: 
![attribution-problem.gif](https://zube.io/files/Autodesk/b634ce5fb538acdecc0fd93a1f07bcc9.gif)

If the user deletes all the text in the field, it should not aggressively restore their name. Instead, it should let them complete their editing. Only if they leave the field blank, upon blur, the name should return. Thanks!

**Comment by maxbates** [comment]
#1654
