### ISSUE TITLE
Delete Project from context menu deletes the currently open project, not the one right-clicked on

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1723]
Open a project, for example, "Project A";
With Project A open, right click on any other project in the list, for example, "Project B";
Select "Delete Project" from the context menu.
Result: Dialog appears referring to deletion of Project A, not Project B. Confirming dialog deletes Project A.
Expected result: Deletion of Project B, which is what the user has right-clicked on.

**Comment by cojofra** [comment]
@maxbates or @duncanmeech could one of you hotfix this?
