### ISSUE TITLE
Autodesk GSL: Editor Team

### ISSUE THREAD

**Issue by dhylbert** [Autodesk/genetic-constructor#1725]
### URL

https://geneticconstructor.bionano.autodesk.com/project/project-8c5f575f-2179-474f-ace7-f9257ce32b2e

### Description

Doesnt work. Is there a plugin or scrit I need to download?

### Additional:

{
  "team": "Autodesk GSL: Editor Team",
  "userId": null,
  "projectId": "project-8c5f575f-2179-474f-ace7-f9257ce32b2e",
  "projectVersion": 9
}

**Comment by cojofra** [comment]
@dhylbert I don't understand the question. do you need some test gsl?
