### ISSUE TITLE
commons page bugs

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1753]
- [x] when clicking on the commons link in the nav I get to the blog it should get me to the commons again - this is correct on the static page - only an issue when you are in the commons already

- [x] when I am signed in already and look at the commons the first 3 nav links don't take me to the section they describe, but just into the app. can we easily detect if a user is signed in or not and show the appropriate nav or fix the auto directs?

- [ ] The Color Exploration Project from Joe does not open - can we fix if it is a general issue?

![Screen_Shot_2017-04-06_at_9_50_58_AM.png](https://zube.io/files/Autodesk/819908677182eab6dde9e13f85b68649.png)

**Comment by maxbates** [comment]
1) will fix
2) Homepage is currently inaccessible when logged in. I can add a flag to the URL (` ?avoidRedirect=true` ), is that ok @jlachoff @cojofra 
3) will have to investigate

**Comment by cojofra** [comment]
2. Yes, that would be good and solve it. thanks!
