### ISSUE TITLE
Blast menu appears in wrong place/has wrong title

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1758]
Spec: https://zpl.io/1o2GUC
1. The label menu label "Extensions" should be "Plugins", per the spec;
2.  The position in the menu is specified to be above the standard group of editing tools, but was tacked on at the bottom instead;
3. The title of the menu item should just be 'BLAST'.
4. Plugins in the menu should be indented, per the spec.

Right now 1 and 3 are inconsistent with the Plugins panel, which leads to confusion for users.

**Comment by cojofra** [comment]
maybe also someone else can take this. 
motivation for triaging high: using blast example to pitch for other plugins for partners and collaborators. should be our text book example.

**Comment by florencio-mazzoldi** [comment]
Justin
