### ISSUE TITLE
Orphaned keystrokes still active

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#1762]
Cmd-F and Cmd-O used to do "Find" (Search) and "Open" (My Projects). We removed the menu system but we never disabled these keystrokes. When you use them currently, the Inventory tab appears to be a blank white rectangle.

**Comment by cojofra** [comment]
covered in Autodesk/genetic-constructor#1517 which is scheduled for the next cycle/sprint
