### ISSUE TITLE
consistent NODE_ENV on client and server

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#828]
Client thinks its in production whenever it's deployed

Server only thinks its in production on the production deployment. Should change NODE_ENV in docker-compose-quickstart

**Comment by maxbates** [comment]
This is an environment variable

**Comment by dhylbert** [comment]
So, you don't want `NODE_ENV` to ever equal `dev` or `qa`? Currently, the environment variable `NODE_ENV` is set to `dev` and `qa` in their respective environments.

This change would not require a code change as the environment variable is set by Jenkins on deploy.

**Comment by maxbates** [comment]
qa should be 'production'

dev can stay, easier to debug
