### ISSUE TITLE
Construct selection auto-focus is not working properly

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#851]
selecting a construct in inventory brought it up in the inspector - but the center panel does not auto-focus the construct

**Comment by maxbates** [comment]
@cojofra is this still a thing

**Comment by cojofra** [comment]
yes

**Comment by maxbates** [comment]
This focus action clears this, when you force a blockId. The action/reducer should check if the projectId is the same, and not clear focus.constructId if it is.

**Comment by jlachoff** [comment]
Also: Should auto-scroll into view, if not in view.
