### ISSUE TITLE
"Change Settings" button is appearing in "Review Assemblies" dialog when viewed after ordering

### ISSUE THREAD

**Issue by jlachoff** [Autodesk/genetic-constructor#888]
According to the spec, this button should be hidden after the order is completed. It should only appear when the user has not yet submitted the order. As is, it can lead to mistakenly ordering multiple times.

**Comment by maxbates** [comment]
@jlachoff is this still valid?

**Comment by jlachoff** [comment]
Yes - the original design of this generation of the ordering dialog specifies that you cannot view the first card in the sequence after submitting. All of the information is summarized on the last card.
