### ISSUE TITLE
Inline text editing

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#934]
<p>Currently, users have a hard time to edit title and description. The current UI does not always come into focus correctly and many online tools have inline editing capabilities so it is somewhat expected these days.</p><p><br></p>

<p>Easier text editing</p>

<p>Less user confusion</p>

<p style="color: rgb(51, 51, 51);">In addition to editing in the Inspector panel, the user should be able to edit text in situ in the following areas of the canvas:</p><ol style="color: rgb(51, 51, 51);"><li>The project name (and description if available)</li><li>Top level construct names</li><li>Blocks</li></ol><p></p><p>It should work the following:</p><ul><li>On hover over the text we show the highlight with the edit icon.</li><li>Clicking on the icon or on the word should open the edit menu</li><li>When you lose focus on the field or hit enter the edit gets saved (we can later use shift+enter to create a new line for description items)</li><li>If you hit esc the edit gets discarded</li><li>If you hit undo, the name change should be undone.</li></ul><p><br></p><p>Max feedback:</p><p><span style="color: rgb(51, 51, 51);text-align: left;float: none;">There is already a component which handles this, which may need to be extended but probably already there (e.g. to pass in custom styles)&nbsp;</span>InputSimple</p><p><br><

Mockups:
![Screen Shot 2016-09-16 at 12.27.58 PM.png](https://d1wgsi1t3wetrk.cloudfront.net/d94e71a06fbe209d96ec1e1ac029db41b007f134.png?Expires=1505590164&Signature=dLDzKwRMhUhZHQks9EBPNKpPSiFjwcTtnUtwgs-J3ROFlfGx0ZLUEy2v5qHCKQlFNCOBUDsgt7uqzsEulb3-zYvfcLs0FIvbJijVEA-hYVxZy2D1ZGQ-x5rSaDP~5aOGTap6xNFVd~YW0-YYvAAiGNujiVkuB6BgPLrrxxoZrF0b9d8t9lC7ipeiyNVswWubbMLZyghfq-x8QrnANJyenmRrtfJEWCQT43DAOMu~QkAWwA8qM6dMZu1HGr~Ji6Kx9wm3lgg0OozrASd5mciW1iqScHuyJTrvsbxZ~ngXYcYIoKWgNbK2r8Z47dQBbDuoW0lugaji74bjB0YAixhGcw__&Key-Pair-Id=APKAJZAZ62TYGJ5PA7LA)

Files:
[inlne_edit.svg](https://dzij0fcr9bmh7.cloudfront.net/1d056aca737499c07ac0c95731fd0b7f450e3ac5.svg)

<p>I the mockup I changed the design a little, so that on hover the text becomes a button and displays the icon. This is better for inline editing on the blocks, where there's already a lot of visual clutter and the solo icon was not working.</p>

[See more on IDEA 018 Inline text editing](https://beta.prodpad.com/ideas/18/about)

**Comment by duncanmeech** [comment]
There is another card for this in review
